{"name": "Создание существующего пользователя", "status": "passed", "description": "Тест проверяет появление ошибки, при попытке создатьпользователя с данными, ранее созданного пользователя", "start": 1724065598965, "stop": 1724065599149, "uuid": "c9dfe3f2-20fd-48b9-b39f-2b035ae601fd", "historyId": "bf15b9abcde6d51ee49afe87de0fdcc2", "testCaseId": "bf15b9abcde6d51ee49afe87de0fdcc2", "fullName": "tests.test_register_user.TestRegisterUser#test_create_duplicate_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_register_user"}, {"name": "subSuite", "value": "TestRegisterUser"}, {"name": "host", "value": "DESKTOP-L3DLL49"}, {"name": "thread", "value": "13308-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_register_user"}]}