{"name": "Изменение данных неавторизованным пользователем", "status": "passed", "description": "Тест проверяет появление ошибки, при попыткиизменить данные неавторизованным пользователем", "parameters": [{"name": "data_user", "value": "'contrerasadriana@example.com'"}], "start": 1723885841757, "stop": 1723885841942, "uuid": "8b2d5b45-2786-4f9a-aa67-fcaaceb9d27c", "historyId": "422eec5d0f195f170eacc1969168c8f8", "testCaseId": "75e3752286952ce47f86b20de866b56d", "fullName": "tests.test_update_user_data.TestUpdateUserData#test_update_user_data_not_authorized", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_user_data"}, {"name": "subSuite", "value": "TestUpdateUserData"}, {"name": "host", "value": "DESKTOP-L3DLL49"}, {"name": "thread", "value": "14372-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_user_data"}]}